server:
  port: 8080

spring:
  application:
    name: pokemonapi
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

pokeapi.host: https://pokeapi.co/api/v2/pokemon/